/**
 * CampusBot Pro — First-time Setup Script
 * Run: node setup.js
 * 
 * This creates your .env file interactively
 */

const fs   = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function setup() {
  console.log(`
╔══════════════════════════════════════════╗
║   🎓 CampusBot Pro — First Time Setup   ║
╚══════════════════════════════════════════╝

I'll help you create your .env file.
You need 2 things ready:
  1. MongoDB Atlas connection string
  2. Google Gemini API key

Press Enter to skip any field and fill it later.
`);

  const mongoUri     = await ask('📦 MongoDB URI: ');
  const geminiKey    = await ask('🤖 Gemini API Key: ');
  const port         = await ask('🔌 Port (press Enter for 5001): ') || '5001';

  const envContent = `# CampusBot Pro — generated by setup.js
MONGO_URI=${mongoUri || 'YOUR_MONGODB_URI_HERE'}
GEMINI_API_KEY=${geminiKey || 'YOUR_GEMINI_KEY_HERE'}
PORT=${port}
NODE_ENV=development
CLIENT_URL=http://localhost:5173
`;

  const envPath = path.join(__dirname, '.env');
  fs.writeFileSync(envPath, envContent);
  rl.close();

  console.log(`
✅ .env file created successfully!

${!mongoUri    ? '⚠️  Remember to fill in MONGO_URI in server/.env\n' : ''}${!geminiKey   ? '⚠️  Remember to fill in GEMINI_API_KEY in server/.env\n' : ''}
Now run:  npm run dev
`);
}

setup().catch(err => { console.error(err); process.exit(1); });
